create table trip
(
    id          bigint generated by default as identity,
    user_id     varchar(255),
    boat        bigint  not null,
    departure   bigint  not null,
    destination bigint  not null,
    passengers  integer not null check (passengers >= 1),
    status     varchar(255),
    primary key (id)
);
