create table trip
(
    id          bigint generated by default as identity,
    user_id     varchar(255),
    boat        bigint not null,
    departure   bigint not null,
    destination bigint not null,
    primary key (id)
);
