/*create table trip
(
    id          bigint generated by default as identity,
    user_id     varchar(255),
    boat        bigint  not null,
    departure   bigint  not null,
    destination bigint  not null,
    passengers  integer not null check (passengers >= 1),
    primary key (id)
);*/


INSERT INTO trip (id, user_id, boat, departure, destination, passengers)
VALUES (1, 'admin', 0, 1, 0, 5)