create table boat
(
    id             bigint generated by default as identity,
    builder        varchar(255),
    name           varchar(255),
    number_of_crew integer not null check (number_of_crew >= 1),
    max_passengers integer not null check (max_passengers >= 1),
    min_passengers integer not null check (min_passengers >= 1),
    primary key (id)
);