create table boat
(
    id             bigint generated by default as identity,
    builder        varchar(255),
    name           varchar(255),
    number_of_crew integer not null check (number_of_crew >= 1),
    primary key (id)
);