/*create table boat
(
    id             bigint generated by default as identity,
    builder        varchar(255),
    name           varchar(255),
    number_of_crew integer not null check (number_of_crew >= 1),
    max_passengers integer not null check (max_passengers >= 1),
    min_passengers integer not null check (min_passengers >= 1),
    primary key (id)
);*/
INSERT INTO boat (id, builder, name, number_of_crew, max_passengers, min_passengers)
VALUES (1, 'Yamaha_Motor_Corporation', 'Batty', 3, 10, 2),
       (2, 'Yamaha_Motor_Corporation', 'Speedy', 20, 100, 20),
       (3, 'Benetti', 'Decisive', 2, 6, 1),
       (4, 'Princess', 'Skybird', 5, 20, 4),
       (5, 'Princess', 'Spice', 10, 100, 10),
       (6, 'Princess', 'Royal_Eagle', 3, 6, 3),
       (7, 'Codecasa', 'Second_Step', 1, 3, 1),
       (8, 'Codecasa', 'Penny', 50, 1000, 400),
       (9, 'Codecasa', 'Sundown', 2, 4, 2),
       (10, 'Lazzara', 'Knocker', 20, 100, 10),
       (11, 'Lazzara', 'Champagne', 3, 15, 10)